### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by rubisco57** [supermemo/SuperMemoBackup#1]
Hi alexis, 
I installed BitShelter successfully, but have been pelted with an unhandled exception when I tried to add a schedule. There seems to be an issue with a volume. My system partition is Bitlocker encrypted and the other one with VeraCrypt to allow file sharing with a Linux partition that I use from time to time - they have no drive letter assigned, as the 'vssadmin List Volumes' command reveals. 
I am running Windows 10, Version 1709, Build 16299. 
I would be more than happy to collaborate with further information!
[BitShelter-UnhandledException-IsVolumeSupported .txt](https://github.com/supermemo/SuperMemoBackup/files/2035048/BitShelter-UnhandledException-IsVolumeSupported.txt)

**Comment by alexis-** [comment]
Hi rubisco,
Thank you, I appreciate the detailed feedback. That report should be enough to fix the issue.
It seem the native VSS API is throwing an exception with one of the volume, due to an unsupported format.

It should be a quick fix, I'll ping you here when it is ready.

**Comment by alexis-** [comment]
Solved on DiscordApp
